"""First

Revision ID: 1e9456722533
Revises: 
Create Date: 2021-10-28 14:58:15.941271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e9456722533'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audience',
    sa.Column('audienceId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('audienceId')
    )
    op.create_table('user',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=45), nullable=True),
    sa.Column('firstName', sa.String(length=45), nullable=True),
    sa.Column('lastName', sa.String(length=45), nullable=True),
    sa.Column('email', sa.String(length=45), nullable=True),
    sa.Column('password', sa.String(length=45), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('userId')
    )
    op.create_table('reserve',
    sa.Column('reserveId', sa.Integer(), nullable=False),
    sa.Column('begin', sa.DateTime(), nullable=True),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('audienceId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['audienceId'], ['audience.audienceId'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.userId'], ),
    sa.PrimaryKeyConstraint('reserveId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reserve')
    op.drop_table('user')
    op.drop_table('audience')
    # ### end Alembic commands ###
