"""changed column password

Revision ID: 825e729bcc70
Revises: fae57eed413a
Create Date: 2021-11-18 13:53:23.816703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '825e729bcc70'
down_revision = 'fae57eed413a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
